- name: Create Azure VM
  hosts: localhost
  connection: local
  become: False
  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{azure_resource_base}}-rg"
      name: "{{azure_resource_base}}-vnet"
      address_prefixes: "10.0.0.0/8"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{azure_resource_base}}-rg"
      name: "{{azure_resource_base}}-subnet"
      address_prefix: "10.0.0.0/16"
      virtual_network: "{{azure_resource_base}}-vnet"
  - name: Create Network Security Group that allows SSH + MySQL
    azure_rm_securitygroup:
      resource_group: "{{azure_resource_base}}-rg"
      name: "{{azure_resource_base}}-nsg"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: MySQL
          protocol: Tcp
          destination_port_range: "3306-3309"
          access: Allow
          priority: 1002
          direction: Inbound
