- name: Create Azure MySQL VMs
  hosts: localhost
  vars:
    vm_names:
      - master1
      - master2
      - slave1
      - slave2
      - haproxy1
  connection: local
  tasks:
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{azure_resource_base}}-rg"
      allocation_method: Static
      name: "{{azure_resource_base}}-{{item}}-pip"
    with_items:
      - "{{ vm_names }}"
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{azure_resource_base}}-rg"
      name: "{{azure_resource_base}}-{{item}}-nic"
      virtual_network: "{{azure_resource_base}}-vnet"
      subnet: "{{azure_resource_base}}-subnet"
      public_ip_name: "{{azure_resource_base}}-{{item}}-pip"
      security_group: "{{azure_resource_base}}-nsg"
    with_items:
      - "{{ vm_names }}"
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{azure_resource_base}}-rg"
      name: "{{azure_resource_base}}-{{item}}-vm"
      vm_size: Standard_DS1_v2
      admin_username: "{{ansible_user}}"
      managed_disk_type: Standard_LRS
      ssh_password_enabled: false
      ssh_public_keys:
        - path: "/home/{{ansible_user}}/.ssh/authorized_keys"
          key_data: "{{ansible_ssh_public_key}}"
      network_interfaces: "{{azure_resource_base}}-{{item}}-nic"
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
#        offer: RHEL
#        publisher: RedHat
#        sku: '6.10'
        version: latest
    with_items:
      - "{{ vm_names }}"
